version: '3.1'

services:
  db:
    image: postgres:12.9-alpine
    container_name: nest-auth-pg
    restart: 'no'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  redis:
    image: redis:6.2.6-alpine
    container_name: nest-auth-redis
    restart: 'no'
    ports:
      - '6379:6379'